# Generated by Django 5.2.3 on 2025-07-07 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='scientific_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scientificarea'),
        ),
    ]
