# Generated by Django 5.2.3 on 2025-07-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_scientific_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='commission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
