# Generated by Django 5.2.3 on 2025-07-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='commission',
            new_name='commission_email',
        ),
    ]
