# Generated by Django 5.1.2 on 2025-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_company_company_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_proposals',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_proposals',
        ),
        migrations.AddField(
            model_name='calendar',
            name='max_proposals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='min_proposals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
