# Generated by Django 5.1.2 on 2025-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_course_max_proposals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='calendar_name',
        ),
        migrations.AddField(
            model_name='calendar',
            name='calendar_semester',
            field=models.PositiveIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='calendar_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
