# Generated by Django 5.1.2 on 2025-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_proposal_proposal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.IntegerField(choices=[(1, 'Project'), (2, 'Internship')]),
        ),
    ]
