# Generated by Django 5.1.2 on 2025-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_proposal_proposal_type_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='calendar_proposal_number',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
