# Generated by Django 5.1.2 on 2025-08-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calendar_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_profile_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_calendar', to='api.calendar'),
        ),
    ]
