# Generated by Django 5.1.2 on 2025-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_student_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects_done',
            field=models.IntegerField(null=True),
        ),
    ]
