# Generated by Django 5.1.2 on 2025-08-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_student_subjects_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='students',
        ),
    ]
