# Generated by Django 5.2.1 on 2025-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_calendar_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
