# Generated by Django 5.2.1 on 2025-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_company_logo_alter_accounts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ident_doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ident_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
