# Generated by Django 5.2.1 on 2025-12-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_student_current_year_alter_student_ident_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(blank=True, max_length=20, null=True)),
                ('new_state', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.candidature')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id_protocol', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='protocols/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('isec_signed_at', models.DateTimeField(blank=True, null=True)),
                ('company_signed_at', models.DateTimeField(blank=True, null=True)),
                ('student_signed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='api.candidature')),
                ('company_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signed_protocols', to=settings.AUTH_USER_MODEL)),
                ('isec_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isec_signed_protocols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

