# Generated by Django 5.2.1 on 2026-01-25 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_student_current_year_alter_student_ident_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_students', to='api.accounts'),
        ),
        migrations.AddField(
            model_name='student',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
