# Generated by Django 5.2.1 on 2026-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_student_current_year_alter_student_ident_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='academic_services_password',
            field=models.CharField(default='servicos_academicos@123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('representative', 'Company Representative'), ('teacher', 'Teacher'), ('academic_services', 'Academic Services')], default='student', max_length=50),
        ),
    ]
