# Generated by Django 5.2.1 on 2026-01-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_candidature_created_at_candidature_last_updated_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_candidaturehistory 
                DROP CONSTRAINT IF EXISTS api_candidaturehisto_candidature_id_2d56cc3f_fk_api_candi;
                
                ALTER TABLE api_candidaturehistory
                ADD CONSTRAINT api_candidaturehisto_candidature_id_2d56cc3f_fk_api_candi
                FOREIGN KEY (candidature_id) 
                REFERENCES api_candidature(id_candidature) 
                ON DELETE CASCADE;
            """,
            reverse_sql="""
                ALTER TABLE api_candidaturehistory 
                DROP CONSTRAINT IF EXISTS api_candidaturehisto_candidature_id_2d56cc3f_fk_api_candi;
                
                ALTER TABLE api_candidaturehistory
                ADD CONSTRAINT api_candidaturehisto_candidature_id_2d56cc3f_fk_api_candi
                FOREIGN KEY (candidature_id) 
                REFERENCES api_candidature(id_candidature);
            """
        ),
    ]
