# Generated by Django 5.2.1 on 2026-01-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_fix_candidature_history_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatureproposal',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='candidatureproposal',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='1 = primeira escolha, 2 = segunda escolha, etc.'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatureproposal',
            unique_together={('candidature', 'priority'), ('candidature', 'proposal')},
        ),
    ]
