# Generated by Django 5.2.1 on 2026-01-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_settings_academic_services_password_and_more'),
        ('api', '0024_fix_candidature_history_cascade'),
    ]

    operations = [
    ]
