# Generated by Django 5.2.1 on 2026-01-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_candidatureproposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='placed_proposal',
            field=models.ForeignKey(blank=True, help_text='Proposta na qual o aluno está atualmente colocado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_candidatures', to='api.proposal'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='placement_attempt',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de colocação (0=não colocado ainda, 1=1ª tentativa, etc.)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('revision', 'Revision'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('protocol_generated', 'Protocol Generated'), ('presidency_signature', 'ISEC Signature'), ('company_signature', 'Company Signature'), ('student_signature', 'Student Signature'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatureproposal',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
