# Generated by Django 5.2.1 on 2026-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260125_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='validation_status',
            field=models.IntegerField(default=0),
        ),
    ]
