# Generated by Django 5.2.1 on 2026-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_student_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
