# Generated by Django 5.2.1 on 2026-01-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_placement_fields_and_states'),
        ('api', '0027_alter_student_validation_status'),
    ]

    operations = [
    ]
