# Generated by Django 5.2.1 on 2026-01-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_notification_settings'),
        ('api', '0028_merge_20260127_0146'),
    ]

    operations = [
    ]
