# Generated by Django 5.2.1 on 2026-01-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_protocol_generation_fields'),
        ('api', '0029_merge_20260127_0353'),
    ]

    operations = [
    ]
