# Generated by Django 5.2.1 on 2026-01-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_calendar_notification_settings'),
        ('api', '0030_merge_20260127_0430'),
    ]

    operations = [
    ]
