# Generated by Django 5.2.1 on 2026-01-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_application_notification_settings'),
        ('api', '0031_merge_20260127_0437'),
    ]

    operations = [
    ]
