# Generated by Django 5.2.1 on 2025-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_scheduling',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_conditions',
            field=models.TextField(null=True),
        ),
    ]
