# Generated by Django 5.2.3 on 2025-07-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposal_proposal_scheduling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_responsible', to='api.teacher'),
        ),
    ]
