# Generated by Django 5.2.3 on 2025-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_commission_course_commission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admins',
        ),
        migrations.AddField(
            model_name='course',
            name='commission',
            field=models.ManyToManyField(blank=True, related_name='course_commission', to='api.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
