# Generated by Django 5.1.2 on 2025-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_course_admins_course_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='protected/curriculums/'),
        ),
    ]
