# Generated by Django 5.1.2 on 2025-07-15 12:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_student_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='protected/curriculums/', validators=[api.models.validate_pdf]),
        ),
    ]
