# Generated by Django 5.1.2 on 2025-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
