# Generated by Django 5.1.2 on 2025-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_calendar_calendar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[(1, 'Project'), (2, 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='work_format',
            field=models.CharField(choices=[(1, 'On-site'), (2, 'Remote'), (3, 'Hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
