# Generated by Django 5.1.2 on 2025-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_proposal_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.IntegerField(choices=[(1, 'Internship'), (2, 'Project')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nif',
            field=models.IntegerField(null=True),
        ),
    ]
