# Generated by Django 5.1.2 on 2025-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_proposal_calendar_proposal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='registrations',
            field=models.DateField(null=True),
        ),
    ]
